[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Aegies"
version = "0.1.0"
description = "Your tiny DSA tracker"
requires-python = ">=3.14"
dependencies = [
    "click",
]

[project.scripts]
aegies = "dsa_tracker.cli:cli"

[project.optional-dependencies]
dev = ["pytest"]